### ISSUE TITLE
Package for Delphi XE4?

### ISSUE THREAD

**Issue by ThomasJaeger** [bonecode/Common#1]
Would you mind adding a package for Delphi XE4?

Thank you in advance!

**Comment by ThomasJaeger** [comment]
Any chance?

**Comment by bonecode** [comment]
Yes, it is coming soon but needs XE4 version of other packages as well.

**Comment by bonecode** [comment]
Added but don't expect me to maintain these XE4 packages. These are common dialogs, forms, frames and units for bonecode projects and I am always using the latest version of Delphi.
